language : node_js
node_js :
 - stable
install:
 - npm install
script:
 - npm test
after_success:
 - npm run coverage
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN_RELEASE
  file: "dist/power-validator.min.js"
  skip_cleanup: true
  on:
    tags: true